---
- hosts: all
  sudo: true
  tasks:
    - name: Add the user 'testuser'
    user:
      name: testuser
    - name: set timezone to Asia/Kolkata
    timezone:
      name: Asia/Kolkata
    - name: Copy random file
    copy:
      src: /home/somefile.txt
      dest: /home/testuser/
    - name: Install Python
      raw: apt -y update && apt install -y python-minimal
      when: check_python.rc != 0
    - name: Install Supervisor
    apt:
      name: supervisor
#      state: present
# Below are steps to install consul
    - name: Download consul latest version
    get_url:
      url: https://releases.hashicorp.com/consul/1.6.1/consul_1.6.1_linux_amd64.zip
      dest: /usr/local/bin
    - name: Unarchive consul file
    unarchive:
      src: /usr/local/bin/consul_1.6.1_linux_amd64.zip
      dest: /usr/local/bin
